server:
  port: 8989
  context-path: /testspring
  jsp-servlet:
    init-parameters:
        development: true
spring:
  mvc:
    view:
      prefix: /
      suffix: .jsp
  http:
    encoding:
      force: true
      charset: utf-8
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: root
    name: idea
    url: jdbc:mysql://localhost:3306/idea
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:com/baizhi/mapper/*Mapper.xml
  type-aliases-package: com.baizhi.entity